### ISSUE TITLE
add base element get function

### ISSUE THREAD

**Issue by mefengl** [adamlui/chatgpt.js#1]
https://github.com/mefengl/chatgpt-utils

If you like, I will add them to this repo

**Comment by adamlui** [comment]
Yes add them I am working on a logo currently

**Comment by adamlui** [comment]
This is a preview btw
![Untitled-4](https://user-images.githubusercontent.com/10906554/225553755-14466914-8e5b-4b30-bebc-af07cf69d688.png)

**Comment by mefengl** [comment]
It appears that the second option is the most visually appealing, particularly the letter 'A'.

**Comment by adamlui** [comment]
I agree, but does the G from 1st row look better? (If so I can combine them)

**Comment by mefengl** [comment]
IDK, then it will be two styles?
